### ISSUE TITLE
Fix an out-of-date definition in metismex.m

### ISSUE THREAD

**Issue by wozy13** [redbKIT/redbKIT#2]
Hi,
I got an error of conflicting types of mwIndex when I was trying to run the install_metismex.m. This error was actually caused by re-definition of mwIndex in metismex.c file

`#if MX_API_VER < 0x07030000
typedef int mwIndex;
typedef int mwSize;
#endif /* MX_API_VER */`

This file was included in the redbKIT-2.2\FEM_library\Mesh\metis-5.0.2\metismex folder. I deleted the definition then install_metismex.m ran smoothly. My OS system is Ubuntu 16.04, with MATLAB R2016a (academic license).

I wish this issue may be helpful.

Zhongyuan Wo

**Comment by FedericoNegri** [comment]
Thank you for your contribution. However this error is affecting metismex.c which is part of the metismex package and not directly of redbKIT. Please report this issue at https://github.com/dgleich/metismex
